/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Button: typeof import('antd')['Button']
  const DatePicker: typeof import('antd')['DatePicker']
  const Input: typeof import('antd')['Input']
}
